# Generated by Django 3.2.18 on 2023-02-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
        migrations.AlterField(
            model_name='post',
            name='longtitute',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=22),
        ),
    ]
