# Generated by Django 3.2.18 on 2023-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
