# Generated by Django 3.2.18 on 2023-03-21 17:22

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20230316_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longtitute',
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=django_google_maps.fields.AddressField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
